import { OrderRequest } from "./types";

export const exampleOrderRequest: OrderRequest = {
  // service_id: 21,
  address: {
    sender: {
      country_code: "PL",
      name: "SKŁADMUZYCZNY.PL Sp. z o.o. Sp. Komandytowa",
      line1: "Skawińska 14",
      line2: "",
      postal_code: "31-066",
      city: "Kraków",
      is_residential: 0,
      contact_person: "SKŁADMUZYCZNY.PL",
      email: "zamowienia@skladmuzyczny.pl",
      phone: "123461842",
      foreign_address_id: "",
    },
    receiver: {
      country_code: "PL",
      name: "Tomasz Kowalski",
      line1: "Korczaka 1 / 1",
      line2: "",
      postal_code: "32-005",
      city: "Niepołomice",
      is_residential: 1,
      contact_person: "Tomasz Kowalski",
      email: "superkowal@smismail.com",
      phone: "500500500",
      foreign_address_id: "",
    },
  },
  pickup: {
    type: "COURIER",
    date: "2024-10-23",
    hours_from: "11:00",
    hours_to: "17:00",
  },
  shipment: [
    {
      dimension1: 40,
      dimension2: 17,
      dimension3: 12,
      weight: 1.0,
      is_nstd: 0,
      shipment_type_code: "PACZKA",
    },
  ],
  content: "Zamowienie 1111 Janko",
  comment: "",
};

export const orderExampleDone = {
  orderDetails: {
    status: 200,
    message: "",
    response: {
      order: {
        id: "123456789",
        supplier: "dpd",
        service_id: "21",
        service_name: "DPD Kurier",
        waybill_number: "1002048656308U",
        pickup: {
          type: "COURIER",
          date: "2024-09-23",
          hours_from: "11:00",
          hours_to: "17:00",
          address_id: null,
        },
        pickup_number: "11111111111111",
        tracking_url:
          "https://www.apaczka.pl/sledz-przesylke/?waybill=1111111111111U",
        status: "DELIVERED",
        shipments_count: 1,
        shipments: [
          {
            shipment_type_code: "PACZKA",
            weight: "1.0",
            weight_billable: "1.0",
            length: "40",
            width: "17",
            height: "12",
            content: "Zamowienie 1111 Janko",
            comment: "",
            waybill_number: "1111111111111U",
            is_nstd: false,
            price: "1120",
            price_vat: 23,
            price_gross: "1378",
          },
        ],
        content: "Zamowienie 1111 Janko",
        comment: "",
        sender: {
          name: "SKŁADMUZYCZNY.PL Sp. z o.o. Sp. Komandytowa",
          contact_person: "SKŁADMUZYCZNY.PL",
          email: "zamowienia@skladmuzyczny.pl",
          phone: "123461842",
          line1: "Skawińska 14",
          line2: "",
          postal_code: "31-066",
          city: "Kraków",
          country_code: "PL",
          foreign_address_id: "",
        },
        receiver: {
          name: "Tomasz Kowalski",
          contact_person: "Tomasz Kowalski",
          email: "superkowal@smismail.com",
          phone: "500500500",
          line1: "Korczaka 1 / 1",
          line2: "",
          postal_code: "32-005",
          city: "Niepołomice",
          country_code: "PL",
          foreign_address_id: "",
        },
        created: "2024-09-23 10:30:00",
        delivered: "2024-09-24 14:33:32",
        price: "1382",
        price_var: 23,
        price_gross: "1700",
        cod: false,
        declaration_value: false,
      },
    },
  },
};
